site_name: Services d'échange de données - 420-4D2-MA - Hiver 2025
site_description: Services d'échange de données - 420-4D2-MA - Hiver 2025 - Collège de Maisonneuve.
site_url: https://archambaultv-prof.github.io/2025H-420-4D2-MA/
nav:
  - Page d'acceuil: index.md
  - Échéancier: echeancier.md
  - Évaluations sommatives: evaluations.md
  - Semaine 1:
    - Plan de leçon: semaine_01/index.md
    - Théorie:
      - Qu'est-ce qu'une donnée?: semaine_01/theorie/definition_donnee.md
      - Avant et après Internet: semaine_01/theorie/avant_apres_internet.md
      - Les différents formats: semaine_01/theorie/format_donnees.md
    - Exercices: semaine_01/exercices/index.md
  - Semaine 2:
    - Plan de leçon: semaine_02/index.md
    - Théorie:
      - Javascript, les bases: semaine_02/theorie/les_bases.md
      - Fonctions: semaine_02/theorie/fonctions.md
      - Objets et tableaux: semaine_02/theorie/objets_tableaux.md
      - JavaScript asynchrone: semaine_02/theorie/asynchrone.md
    - Exercices: semaine_02/exercices/index.md
  - Semaine 3:
    - Plan de leçon: semaine_03/index.md
    - Théorie:
      - Espace de nom: semaine_03/theorie/scope.md
      - Stateless vs Stateful: semaine_03/theorie/stateless_stateful.md
      - Exporter et importer une classe: semaine_03/theorie/export.md
    - Exercice 1: semaine_03/exercice_1.md
  - Semaine 4:
    - Plan de leçon: semaine_04/index.md
    - Théorie:
      - Express js: semaine_04/theorie/expressjs.md
      - Sqlite3 et Knex: semaine_04/theorie/sqlite3_knex.md
      - Envoie de données: semaine_04/theorie/envoie_csv_json.md
    - Exercice 1: semaine_04/exercices/index.md
  - Semaine 5:
    - Plan de leçon: semaine_05/index.md
    - Théorie:
      - Micro service: semaine_05/theorie/micro-service.md
      - Soap: semaine_05/theorie/soap-rest.md
    - Exercice 2: semaine_05/exercice_2.md
theme:
  name: material
  logo: assets/images/logo-white.svg
  favicon: assets/images/favicon.png
  language: fr
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
repo_url: https://github.com/archambaultv-prof/2025H-420-4D2-MA
copyright: Le contenu de ce site est sous licence <a href="https://creativecommons.org/licenses/by/4.0/deed.fr">CC-BY 4.0</a>.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins: 
  - social
  - search
